### ISSUE TITLE
Il sample fallisce con "The key op_name was not present in the dictionary"

### ISSUE THREAD

**Issue by maiorfi** [italia/spid-cie-oidc-aspnetcore#19]
Ho seguito le istruzioni riportate qui:

https://github.com/italia/spid-cie-oidc-aspnetcore/blob/main/SAMPLE.md

Ma nei log del container che esegue l'applicazione ASP.NET Core ho la seguente eccezione:

```
2023-02-28 11:43:28 fail: Microsoft.AspNetCore.Server.Kestrel[13]
2023-02-28 11:43:28       Connection id "0HMOPF242K6Q8", Request id "0HMOPF242K6Q8:00000003": An unhandled exception was thrown by the application.
2023-02-28 11:43:28       System.AggregateException: One or more errors occurred. (The given key 'op_name' was not present in the dictionary.)
2023-02-28 11:43:28        ---> System.Collections.Generic.KeyNotFoundException: The given key 'op_name' was not present in the dictionary.
2023-02-28 11:43:28          at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2023-02-28 11:43:28          at Spid.Cie.OIDC.AspNetCore.Services.IdentityProvidersHandler.CreateSpidIdentityProvider(IdPEntityConfiguration conf)
2023-02-28 11:43:28          at Spid.Cie.OIDC.AspNetCore.Services.IdentityProvidersHandler.GetIdentityProviders()
2023-02-28 11:43:28          at Spid.Cie.OIDC.AspNetCore.Services.Defaults.DefaultIdentityProviderSelector.GetSelectedIdentityProvider()
2023-02-28 11:43:28          at Spid.Cie.OIDC.AspNetCore.Configuration.OpenIdConnectOptionsProvider.<>c__DisplayClass9_0.<<Get>b__0>d.MoveNext()
2023-02-28 11:43:28          --- End of inner exception stack trace ---
2023-02-28 11:43:28          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2023-02-28 11:43:28          at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2023-02-28 11:43:28          at System.Threading.Tasks.Task`1.get_Result()
2023-02-28 11:43:28          at Spid.Cie.OIDC.AspNetCore.Configuration.OpenIdConnectOptionsProvider.Get(String name)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2023-02-28 11:43:28          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Segnalo che quando eseguo il "docker-compose up" ho 2 warning che riportano:

```
WARN[0000] The "APPDATA" variable is not set. Defaulting to a blank string.
```

Dove dovrebbe puntare questa variabile?

Grazie.

**Comment by MarcoTesta-EP** [comment]
Stesso problema anche io...

**Comment by danielegiallonardo** [comment]
La libreria è stata aggiornata, con la versione 1.0.0, rispetto alle attuali linee guida
