### ISSUE TITLE
"System.NullReferenceException: Object reference not set to an instance of an object." in Microsoft.AspNetCore.Authentication.OpenIdConnect

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/spid-cie-oidc-aspnetcore#25]
Sto usando l'ambiente di test djago, come da documentazione ed il replay party djago mi funziona correttamente e riesco a loggarmi sia con admin che come user.
Eseguendo invece il progetto di test aspnetcore (in locale), dopo aver fatto login con l'utente user (ma anche admin ho lo stesso problema), e dopo la visualizzazione della schermata che mi chiede il consenso di condivide i dati, quando clicco sul pulsante "AGREE" ottengo la seguente eccezione, all'interno della libreria Microsoft OpenIdConnect:

```
System.Exception: An error was encountered while handling the remote login.
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Spid.Cie.OIDC.AspNetCore.Middlewares.TrustMarkStatusOpenIdFederationMiddleware.Invoke(HttpContext context, IRelyingPartiesHandler rpHandler, IAggregatorsHandler aggHandler, ICryptoService cryptoService) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\TrustMarkStatusOpenIdFederationMiddleware.cs:line 31
         at Spid.Cie.OIDC.AspNetCore.Middlewares.ListOpenIdFederationMiddleware.Invoke(HttpContext context, IRelyingPartiesHandler rpHandler, IAggregatorsHandler aggHandler, ICryptoService cryptoService) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\ListOpenIdFederationMiddleware.cs:line 30
         at Spid.Cie.OIDC.AspNetCore.Middlewares.FetchOpenIdFederationMiddleware.Invoke(HttpContext context, IRelyingPartiesHandler rpHandler, IAggregatorsHandler aggHandler, ICryptoService cryptoService) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\FetchOpenIdFederationMiddleware.cs:line 32
         at Spid.Cie.OIDC.AspNetCore.Middlewares.ResolveOpenIdFederationMiddleware.Invoke(HttpContext context, IRelyingPartiesHandler rpHandler, IAggregatorsHandler aggHandler, ICryptoService cryptoService, ITrustChainManager trustChainManager) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\ResolveOpenIdFederationMiddleware.cs:line 32
         at Spid.Cie.OIDC.AspNetCore.Middlewares.RPOpenIdFederationMiddleware.Invoke(HttpContext context, IRelyingPartiesHandler rpHandler, IAggregatorsHandler aggregatorsHandler, ICryptoService cryptoService) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\RPOpenIdFederationMiddleware.cs:line 28
         at Spid.Cie.OIDC.AspNetCore.Middlewares.CallbackRewriteMiddleware.Invoke(HttpContext context) in C:\Sources\spid-cie-oidc-aspnetcore\src\Spid.Cie.OIDC.AspNetCore\Middlewares\CallbackRewriteMiddleware.cs:line 26
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)



```

Quali potrebbero essere le cause? Qualche suggerimento per poter indagare meglio il problema?

Grazie

**Comment by marco-maroni-spot-software** [comment]
Una cosa che ho notato è che la configurazione generata dall'esempio per il file .well-known/openid-federation/json manca degli attributi "x5c" e "alg" nella sezione keys, questi:

```
{
...
       "x5c": [
          "MIIGIjCCBAqgAwIBAg...."
        ],
        "alg": "RS256"
}
```
quello generato è così:

```
  "jwks": {
    "keys": [
      {
        "kty": "RSA",
        "use": "sig",
        "kid": "B5D9B00247B14DF93690A2E4F763C12357EF69F8",
        "e": "AQAB",
        "n": "mGLk2E8AziGBAmj8XuU-..."
      }
    ]

```

Non so se questo può essere rilevante
